package org.apache.jsp.sberUL;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.qmatic.web.staff.Utils;
import com.qmatic.ConnectionContext;
import javax.servlet.http.*;
import javax.servlet.*;
import com.qmatic.QwinFactory.QWinFactory;
import com.qmatic.scripting.Script;
import com.qmatic.scripting.ScriptManager;
import webwork.action.ActionSupport;

public final class pult_qsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("﻿\r\n");
      out.write("\r\n");

if(request.getParameter("close")!= null) {
    ScriptManager sm = ConnectionContext.getQWinFactory().getScriptManager();
    try
    {
		Script s = sm.createScript("run", "W="+request.getParameter("workstation")+"IF(COUNTER_CUSTOMER_PRESENT(W) EQ 1) BEGIN U=TIME_NO-COUNTER_CUSTOMER_ITEM(W ITEM_NEXT) IF((U*2) LE ((ARRAY(501)+ARRAY(500)))) BEGIN SETARRAY(5730+W 1) FUNC_INSERT_LAST(W 5 COUNTER_CUSTOMER_ITEM(W ITEM_NUMBER) 142 0) END END FUNC_COUNTER_CLOSE(W) SETARRAY(2900+W 0)");
		s.execute();
		sm.killScript(s);
    } catch (Exception e) {
    }
	}
	
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- VER 5.0 21.08.2013 -->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Пульт операциониста ЮЛ</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("<script  language=javascript>\r\n");
      out.write("var ticket_alert=\"\";\r\n");
      out.write("var sbros_call;\r\n");
      out.write("function createXMLHttpRequest() {\r\n");
      out.write("  try { return new XMLHttpRequest(); } catch(e) {}\r\n");
      out.write("  try { return new ActiveXObject('Msxml2.XMLHTTP'); } catch (e) {}\r\n");
      out.write("  try { return new ActiveXObject('Microsoft.XMLHTTP'); } catch (e) {}\r\n");
      out.write("  throw 'XMLHttpRequest not supported';\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("var HTTP_TIMEOUT = 10;\r\n");
      out.write("\r\n");
      out.write("function httpRequest(url, onSuccess, onFail, postData, timeout) {\r\n");
      out.write("\r\n");
      out.write("  var req = createXMLHttpRequest();\r\n");
      out.write("  var method = postData ? 'POST' : 'GET';\r\n");
      out.write("  req.open(method, url, true);\r\n");
      out.write("  req.setRequestHeader('User-Agent', 'XMLHTTP/1.0');\r\n");
      out.write("  if (postData) {\r\n");
      out.write("    req.setRequestHeader('Content-type','application/x-www-form-urlencoded');\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  var timer = null;\r\n");
      out.write("  if (!timeout) timeout = HTTP_TIMEOUT;\r\n");
      out.write("  if (timeout != -1) {\r\n");
      out.write("    timer = setTimeout(httpTimeoutClosure(req, onFail), timeout);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  req.onreadystatechange = httpStatusChangeClosure(req, onSuccess, onFail, timer);\r\n");
      out.write("    req.send(postData);\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("function httpTimeoutClosure(req, onFail) {\r\n");
      out.write("  return function() {\r\n");
      out.write("   req.onreadystatechange = null;\r\n");
      out.write("    try {req.abort()}\r\n");
      out.write("   finally {if (onFail) onFail(req)}\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function httpStatusChangeClosure(req, onSuccess, onFail, timer) {\r\n");
      out.write("  return function() {\r\n");
      out.write("    if (req.readyState != 4) return;\r\n");
      out.write("    if (timer) clearTimeout(timer);\r\n");
      out.write("    if (req.status != 200 && req.status != 304) {\r\n");
      out.write("      if (onFail) onFail(req);\r\n");
      out.write("      return;\r\n");
      out.write("    }    \r\n");
      out.write("    if (onSuccess) onSuccess(req);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function page2() {\r\n");
      out.write("\tdocument.innerHTML='sdfsdfsdfsdf';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/qevent.js\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=ajax.js language=javascript></script>\r\n");
      out.write("<script src=script.js language=javascript></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("var img=new Array();\r\n");
      out.write("img[0]=new Image();\r\n");
      out.write("img[0].src='images/button_d.gif';\r\n");
      out.write("img[1]=new Image();\r\n");
      out.write("img[1].src='images/next_d.gif';\r\n");
      out.write("img[2]=new Image();\r\n");
      out.write("img[2].src='images/button_a.gif';\r\n");
      out.write("img[3]=new Image();\r\n");
      out.write("img[3].src='images/next_a.gif';\r\n");
      out.write("image_1='url('+img[0].src+')';\r\n");
      out.write("image_2='url('+img[1].src+')';\r\n");
      out.write("image_3='url('+img[2].src+')';\r\n");
      out.write("image_4='url('+img[3].src+')';\r\n");
      out.write("\r\n");
      out.write("image2_1='url(\"'+img[0].src+'\")';\r\n");
      out.write("image2_2='url(\"'+img[1].src+'\")';\r\n");
      out.write("image2_3='url(\"'+img[2].src+'\")';\r\n");
      out.write("image2_4='url(\"'+img[3].src+'\")';\r\n");
      out.write("\t\r\n");
      out.write("function getVarValueFromURL(url, varName) { //для получение значений из URL\r\n");
      out.write("\tvar query = url.substring(url.indexOf('?') + 1);\r\n");
      out.write("\tvar vars = query.split(\"&\");\r\n");
      out.write("\tfor (var i=0;i<vars.length;i++) {\r\n");
      out.write("\t\tvar pair = vars[i].split(\"=\");\r\n");
      out.write("\t\tif (pair[0] == varName) {\r\n");
      out.write("\t\t\treturn pair[1];\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn null;\r\n");
      out.write("} ;\r\n");
      out.write("\r\n");
      out.write("var no_event=false;\r\n");
      out.write("var ws=getVarValueFromURL(document.URL ,'workstation')*1;\r\n");
      out.write("var logincod=getVarValueFromURL(document.URL ,'logincod')*1;\r\n");
      out.write("var pereriv_work=false;\r\n");
      out.write("var error_state=0;\r\n");
      out.write("var customer_present=0;\r\n");
      out.write("var counter_open=0;\r\n");
      out.write("var counter_item_button=0; //номер кнопки обсл. клиента\r\n");
      out.write("var counter_transaction_time=0;\r\n");
      out.write("var taktika=0;\r\n");
      out.write("var takt_array_=new Array();\r\n");
      out.write("var taktika_norma=1;\r\n");
      out.write("\r\n");
      out.write("var array_495=30;\t//{время обсл. клиента более которого красный}\r\n");
      out.write("var array_500=7; \t//{доступность повторного вызова} \r\n");
      out.write("var array_501=20; \t//{доступность сброса вызова} \r\n");
      out.write("var array_7000_w=0; //{доступность кнопки спец. рег.} \r\n");
      out.write("\r\n");
      out.write("qwin_event.trig = function(eventType, unit, payload){\r\n");
      out.write("\r\n");
      out.write("if(eventType==5) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t//alert(\"Событие вызов payload=\"+payload);\r\n");
      out.write("\t\tif(unit==ws & no_event==false) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchange_avalible('in_work',0);\r\n");
      out.write("\t\t\tsbrf.log(\"Событие вызов payload=\"+payload);\r\n");
      out.write("\t\t//\talert(\"Событие вызов payload=\"+payload);\r\n");
      out.write("\t\t\trun_qwin('update',0);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tif(eventType==143) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("}\r\n");
      out.write("qwin_event.setEvents = function(){\r\n");
      out.write("\tqwin_event.waitForEventTrig(\"5.143\");\r\n");
      out.write("}\r\n");
      out.write("qwin_event.setEvents();\r\n");
      out.write("var blink_a=0;\r\n");
      out.write("blink_b=0; //Мигалки\r\n");
      out.write("function loadButtons() { //Первичная загрузка кнопок\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tsetInterval(function(){\r\n");
      out.write("\t\tvar now = new Date();\r\n");
      out.write("\t\tvar clock = document.getElementById('clock');\r\n");
      out.write("\t\tclock.innerHTML = now.toLocaleTimeString();\r\n");
      out.write("\t}, 1000);\r\n");
      out.write("\tvar d=new Date();\r\n");
      out.write("\tvar day=d.getDate();\r\n");
      out.write("\tvar month=d.getMonth() + 1;\r\n");
      out.write("\tvar year=d.getFullYear();\r\n");
      out.write("\t//document.write(day + \".\" + month + \".\" + year);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById('clock_date').innerHTML=day + \".\" + month + \".\" + year;\r\n");
      out.write("\tdocument.getElementById('counter').innerHTML=\"Окно \"+ws;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar close=getVarValueFromURL(document.URL ,'close')*1;\r\n");
      out.write("\tif(close==1) {\r\n");
      out.write("\t\trun_qwin('close',0);\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\ttype_avalible(0); //кнопки по умолчанию\r\n");
      out.write("\trun_qwin('update_logon',0); //обновляем содержимое пульта...\r\n");
      out.write("\r\n");
      out.write("\tupdate();////////////////////////////////////////////////////////////////////////////////////////////////////!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("} //end loadButtons()\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function sbros()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.getElementById(\"next\").value=\"Следующий\";\r\n");
      out.write("\tchange_avalible('otlozh',0);\r\n");
      out.write("\tchange_avalible('number_call',0);\r\n");
      out.write("\tchange_avalible('registration',1);\r\n");
      out.write("\tchange_avalible('pereadres',1);\r\n");
      out.write("\tchange_avalible('pereriv',0);\r\n");
      out.write("\tdocument.getElementById('msg_log').style.display='none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function blink() { //Мигание номера\r\n");
      out.write("\tel=document.getElementById(\"display\")\r\n");
      out.write("\tif(blink_a==0) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(blink_b==1)\tel.style.display='block';\r\n");
      out.write("\t\tif(customer_present==1) {\r\n");
      out.write("\t\t\ttype_avalible(1); //После мигания номера окно переходит в режим обслуживания\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\ttype_avalible(3);\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t}\r\n");
      out.write("\tif(blink_a>0)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(blink_b==1) {el.style.display='block'; blink_b=0;}\r\n");
      out.write("\t\telse {el.style.display='none'; blink_b=1;}\r\n");
      out.write("\t\tblink_a=blink_a-1;\r\n");
      out.write("\t\tsetTimeout('blink()', 500);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sd(ticket,to,type) //отображение А101 переведе в .... val=ticket number,type=window or operation\r\n");
      out.write("{\r\n");
      out.write("\ttype_avalible(4);\r\n");
      out.write("\tif(type==1) //to window\r\n");
      out.write("\t{\r\n");
      out.write("\tif(to>1000 && to<2000)\r\n");
      out.write("\t\tto=to-1000;\r\n");
      out.write("\tif(to>2000)\r\n");
      out.write("\t\tto=to-2000;\r\n");
      out.write("\t\tdocument.getElementById('msg_log').innerHTML=\"<table topmargin=0 cellpadding=0 align=center cellspacing=0 background='images/display.gif' width=252 height=66><tr><td><font color='#00ff00'><b><center>\"+ticket+\"<br>переадресован<br>в окно \"+to+\"</center><b></font></td></tr></table>\";\r\n");
      out.write("\t} else {//to operation\r\n");
      out.write("\t\tdocument.getElementById('msg_log').innerHTML=\"<table topmargin=0 cellpadding=0 align=center cellspacing=0 background='images/display.gif' width=252 height=66><tr><td><font color='#00ff00'><b><center>\"+ticket+\"<br>переадресован на<br> операцию \"+to+\"</center><b></font></td></tr></table>\";\r\n");
      out.write("\t};\r\n");
      out.write("\tdocument.getElementById('msg_log').style.display='block';\r\n");
      out.write("hide_top_msg(0); //скрытие дива top_msg\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function svetofor() { //progreess bar obsl customer\r\n");
      out.write("\r\n");
      out.write("\tel=document.getElementById('svet2');\r\n");
      out.write("\tif(customer_present== 1 && ((counter_item_button)!=183))\r\n");
      out.write("\t{\r\n");
      out.write("\t\r\n");
      out.write("\t\tcounter_transaction_time+=1;\r\n");
      out.write("\t\tif(counter_transaction_time>=taktika_norma+2)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tel.style.backgroundColor='red';\r\n");
      out.write("\t\t\tel.style.width='126px';\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tel.style.background='rgb(119,161,23)';\r\n");
      out.write("\t\t\tif(taktika_norma!=0) {\r\n");
      out.write("\t\t\t\tel.style.width=Math.round((126/taktika_norma)*counter_transaction_time)+'px';\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tel.style.width='0px';;\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tminut=Math.round(((counter_transaction_time*2)/60)-0.5);\r\n");
      out.write("\tsecond=Math.round(((counter_transaction_time*2-(minut*60)))-0.5);\r\n");
      out.write("\tif(minut<10)\r\n");
      out.write("\t\tminut=\"0\"+minut;\r\n");
      out.write("\tif(second<10)\r\n");
      out.write("\t\tsecond=\"0\"+second;\r\n");
      out.write("\tdocument.getElementById('obsl').innerHTML =minut+\":\"+second;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//\tsetTimeout('svetofor()', 2000);\r\n");
      out.write("};\r\n");
      out.write("function getChar(event) {\r\n");
      out.write("if (event.keyCode == 27 || event.which == 27) { hide_top_msg(0); }// спец. символ\r\n");
      out.write("else return false;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body_content\" onload=\"loadButtons(); svetofor();\" style=\"overflow:hidden\" scroll=\"no\" onkeypress=\"getChar(event);\">\r\n");
      out.write("<div id='msg_log' class=div_log style=\"display:none;\"></div>\r\n");
      out.write("<div class=div_msg id='msg_top'></div>\r\n");
      out.write("<div class=div_msg id='msg_timeout'><br><br><center><img src=\"images/loading.gif\"><br><br><font color=white size=+2><b>ЗАГРУЗКА...</b></font></center></div>\r\n");
      out.write("<table width=277 height=418 cellspacing=0 cellpadding=0>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t<td colspan=2 height='15px' class=\"titletext\" align=center>\r\n");
      out.write("\t\t<a id='clock_date' align=right>12:23:33</a>\r\n");
      out.write("\t\t\t\t\t<a id='clock' align=right>12:23:33</a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=66 align=center>\r\n");
      out.write("\t\t<td colspan=2>\r\n");
      out.write("\t\t<div class=\"tdisplay\">\r\n");
      out.write("\t\t\t<div id='display' width=252 height=66>\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr align=center>\r\n");
      out.write("\t\t<td colspan=2 height='13px'>\r\n");
      out.write("\t\t<div id='custitemcard' class=\"card_text\"></div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("<!--\t<tr>\r\n");
      out.write("\t\t<td colspan=2 height='15px' class=\"titletext\">\r\n");
      out.write("\t\tВремя\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>-->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=2 height='40px' align=center>\r\n");
      out.write("\t\t\t<table width=253 height=40 cellspacing=0 cellpadding=0 border=0 class=\"info1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td rowspan=2 width=90px>\r\n");
      out.write("\t\t\t\t\tТакт/норм.<br>время: <a id='takt'></a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\tОбслуживание: <a  id='obsl'></a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=17px>\r\n");
      out.write("\t\t\t\t\t<td valign=top align=left>\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=0 cellpadding=0 id='svet2'><tr><td></td></tr></table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<!--<tr>\r\n");
      out.write("\t\t<td colspan=2 height='15px' class=\"titletext\">\r\n");
      out.write("\t\tКоличество ожидающих\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>-->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=2 height='40px' align=center>\r\n");
      out.write("\t\t\t<table width=253 height=40 cellspacing=0 cellpadding=0 class=\"info2\" table=1>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=50%>\r\n");
      out.write("\t\t\t\t\tВсего: <a id='vseg'></a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t&nbsp;Операции: \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=2 id='oper' align=center style=\"font-size:7pt;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=2 height='36px' align=center>\r\n");
      out.write("\t\t\t<table  cellspacing=0 cellpadding=0 ><tr><td><input type=\"button\" class=\"next\" id='next' onClick=\"doSomething(this);\" value='Следующий'/></td></tr></table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height='36px' width=50% align=center class=\"bleft\">\r\n");
      out.write("\t\t\t<table  cellspacing=0 cellpadding=0><tr><td><input type=\"button\" class=\"button\" id='recall' onClick=\"doSomething(this);\" value='Повторный вызов'/></td></tr></table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td height='36px' width=50% align=center class=\"bright\">\r\n");
      out.write("\t\t\t<table cellspacing=0 cellpadding=0><tr><td><input type=\"button\" class=\"button\" id='otlozh' onClick=\"doSomething(this);\" value='Отложить клиента'/></td></tr></table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height='36px' width=50% align=center class=\"bleft\">\r\n");
      out.write("\t\t\t<table cellspacing=0 cellpadding=0><tr><td><input type=\"button\" class=\"button\" id='number_call' onClick=\"doSomething(this);\" value='Вызвать по номеру'/></td></tr></table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td height='36px' width=50% align=center class=\"bright\">\r\n");
      out.write("\t\t\t<table cellspacing=0 cellpadding=0><tr><td><button class=\"button\" id='registration' onClick=\"doSomething(this);\">Специальная<br>регистрация</button></td></tr></table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height='36px' width=50% align=center class=\"bleft\">\r\n");
      out.write("\t\t\t<table cellspacing=0 cellpadding=0><tr><td><input type=\"button\" class=\"button\" id='pereadres' onClick=\"doSomething(this);\" value='Переадресация'/></td></tr></table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td height='36px' width=50% align=center class=\"bright\" >\r\n");
      out.write("\t\t\t<table cellspacing=0 cellpadding=0><tr><td><input type=\"button\" class=\"button\" id='pereriv' onClick=\"doSomething(this);\" value='Перерыв'/></td></tr></table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td colspan=2 height='36px' align=center>\r\n");
      out.write("\t\t\t<table  cellspacing=0 cellpadding=0 ><tr><td><input type=\"button\" class=\"next\" id='in_work' onClick=\"doSomething(this);\" value='Внутренние работы'/></td></tr></table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=2 height='15px' class=\"titletext\">\r\n");
      out.write("\t\tСтатистика за день\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=2 height='40px' align=center>\r\n");
      out.write("\t\t\t<table width=253 height=40 cellspacing=0 cellpadding=0 class=\"info3\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=65px>\r\n");
      out.write("\t\t\t\t\tТалонов: <a id='cst'></a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\tСред. время обслуж.: <a id='att'></a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr><tr>\r\n");
      out.write("\t\t<td colspan=2 height='40px' align=center>\r\n");
      out.write("\t\t\t<table width=253 height=40 cellspacing=0 cellpadding=0 class=\"info3\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=center>\r\n");
      out.write("\t\t\t\t\t<a id='counter' align=left>Окно 12</a> (<a id='login' align=right>логин</a>)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
